/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.LP34CPrimeiroProjeto;

public class App {

    public static void main(String[] args) {
        
        System.out.println("Olá mundo");
        System.out.println("Meu segundo comando de saída");
        
    }
}
